"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Download, CalendarDays, Clock, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { pdf, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { useData } from "@/lib/data-context";

// PDF Styles
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", color: "#0f172a" },
  header: { marginBottom: 30 },
  logoText: { fontSize: 24, fontWeight: "bold", color: "#0f172a", marginBottom: 4 },
  companyName: { fontSize: 14, color: "#64748b" },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 20, marginTop: 10 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", marginBottom: 30 },
  statBox: { width: "50%", marginBottom: 15 },
  statLabel: { fontSize: 10, color: "#64748b", textTransform: "uppercase", marginBottom: 4 },
  statValue: { fontSize: 18, fontWeight: "bold" },
  table: { width: "100%", borderTop: "1px solid #e2e8f0", marginTop: 20 },
  tableHeader: { flexDirection: "row", borderBottom: "1px solid #e2e8f0", paddingVertical: 8, backgroundColor: "#f8fafc" },
  tableRow: { flexDirection: "row", borderBottom: "1px solid #e2e8f0", paddingVertical: 8 },
  colDate: { width: "15%", fontSize: 10 },
  colAmount: { width: "20%", fontSize: 10, fontWeight: "bold" },
  colReason: { width: "45%", fontSize: 10 },
  colStatus: { width: "20%", fontSize: 10 },
  footer: { position: "absolute", bottom: 40, left: 40, right: 40, textAlign: "center", fontSize: 10, color: "#94a3b8" }
});

const ReportPDF = ({ period, stats, exceptions }: { period: string, stats: any, exceptions: any[] }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.logoText}>ReconFlow</Text>
        <Text style={styles.companyName}>Acme Corp</Text>
      </View>
      
      <Text style={styles.title}>Reconciliation Report ({period})</Text>
      
      <View style={styles.statsGrid}>
        <View style={styles.statBox}>
          <Text style={styles.statLabel}>Total Transactions</Text>
          <Text style={styles.statValue}>{stats.total}</Text>
        </View>
        <View style={styles.statBox}>
          <Text style={styles.statLabel}>Auto-matched</Text>
          <Text style={styles.statValue}>{stats.autoMatched} ({stats.percentage}%)</Text>
        </View>
        <View style={styles.statBox}>
          <Text style={styles.statLabel}>Manually Reviewed</Text>
          <Text style={styles.statValue}>{stats.manualReview}</Text>
        </View>
        <View style={styles.statBox}>
          <Text style={styles.statLabel}>Exceptions Resolved</Text>
          <Text style={styles.statValue}>{stats.exceptions}</Text>
        </View>
      </View>
      
      <Text style={{ fontSize: 14, fontWeight: "bold", marginTop: 20, marginBottom: 10 }}>Top Exceptions Summary</Text>
      <View style={styles.table}>
        <View style={styles.tableHeader}>
          <Text style={styles.colDate}>Date</Text>
          <Text style={styles.colAmount}>Amount</Text>
          <Text style={styles.colReason}>Reason</Text>
          <Text style={styles.colStatus}>Status</Text>
        </View>
        {exceptions.map((exc, i) => (
          <View key={i} style={styles.tableRow}>
            <Text style={styles.colDate}>{exc.date}</Text>
            <Text style={styles.colAmount}>
              {new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Math.abs(exc.amount))}
            </Text>
            <Text style={styles.colReason}>{exc.reasonTag}</Text>
            <Text style={styles.colStatus}>{exc.status}</Text>
          </View>
        ))}
      </View>
      
      <Text style={styles.footer}>Generated by ReconFlow · {period}</Text>
    </Page>
  </Document>
);

export default function ReportsPage() {
  const [selectedPeriod, setSelectedPeriod] = useState<string>("June 2026");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [stats, setStats] = useState({
    total: "0",
    autoMatched: "0",
    percentage: "0.0",
    manualReview: "0",
    exceptions: "0"
  });
  const [topExceptions, setTopExceptions] = useState<any[]>([]);

  // Derived display values from real stats
  const totalNum = Number(stats.total) || 0;
  const autoNum = Number(stats.autoMatched) || 0;
  const manualNum = Number(stats.manualReview) || 0;
  const exceptionNum = Number(stats.exceptions) || 0;

  const autoPercent = totalNum > 0 ? Math.round((autoNum / totalNum) * 100) : 0;
  const manualPercent = totalNum > 0 ? Math.round((manualNum / totalNum) * 100) : 0;
  const exceptionPercent = totalNum > 0 ? Math.max(0, 100 - autoPercent - manualPercent) : 0;

  const healthScore = totalNum > 0
    ? Math.min(100, Math.round(
        (autoNum / totalNum) * 70 +
        (1 - Math.min(1, exceptionNum / Math.max(1, totalNum))) * 30
      ))
    : null;

  const timeSavedHours = Math.round((autoNum * 3) / 60);

  useEffect(() => {
    if (!selectedPeriod) return;

    const fetchStats = async () => {
      setIsLoading(true);
      try {
        // Calculate period bounds based on selection
        let periodStart, periodEnd;
        const now = new Date();
        
        if (selectedPeriod === "Last 30 days") {
          periodEnd = now;
          periodStart = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
        } else if (selectedPeriod === "Custom range") {
          periodStart = new Date(now.getFullYear(), 0, 1); // Mock for now
          periodEnd = now;
        } else {
          // It's a month name like "June 2026"
          const [monthStr, yearStr] = selectedPeriod.split(" ");
          const monthIndex = new Date(`${monthStr} 1, 2000`).getMonth();
          const year = parseInt(yearStr);
          periodStart = new Date(year, monthIndex, 1);
          periodEnd = new Date(year, monthIndex + 1, 0); // Last day of month
        }

        const res = await fetch(`/api/reports/summary?periodStart=${periodStart.toISOString()}&periodEnd=${periodEnd.toISOString()}`);
        if (res.ok) {
          const data = await res.json();
          setStats(data.stats);
          setTopExceptions(data.topExceptions || []);
        }
      } catch (error) {
        console.error("Failed to fetch reports summary", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchStats();
  }, [selectedPeriod]);

  const handleGeneratePDF = async () => {
    if (!selectedPeriod) {
      toast.error("Please select a period first.");
      return;
    }
    
    setIsGenerating(true);
    
    try {
      const blob = await pdf(
        <ReportPDF period={selectedPeriod} stats={stats} exceptions={topExceptions} />
      ).toBlob();
      
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `ReconFlow_${selectedPeriod.replace(/ /g, "_")}_Report.pdf`;
      link.click();
      URL.revokeObjectURL(url);
      toast.success("PDF report generated successfully!");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate PDF");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="p-4 sm:p-6 flex flex-col gap-6 h-full font-sans text-slate-900 mx-auto w-full max-w-5xl">
      {/* Top Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 shrink-0">
        <h1 className="text-2xl font-bold tracking-tight text-slate-900">Month-end report</h1>
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
          <div className="relative">
            <select
              title="Select period"
              className="appearance-none h-10 pl-3 pr-8 w-full sm:w-[180px] rounded-md border border-slate-300 bg-white text-sm font-medium focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-slate-900"
              value={selectedPeriod}
              onChange={(e) => setSelectedPeriod(e.target.value)}
            >
              <option value="">Select period...</option>
              <option value="June 2026">June 2026</option>
              <option value="May 2026">May 2026</option>
              <option value="April 2026">April 2026</option>
              <option value="Last 30 days">Last 30 days</option>
              <option value="Custom range">Custom range</option>
            </select>
            <div className="absolute right-3 top-3 pointer-events-none text-slate-500">
              <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4.93179 5.43179C4.75605 5.60753 4.75605 5.89245 4.93179 6.06819L7.43179 8.56819C7.60753 8.74393 7.89245 8.74393 8.06819 8.56819L10.5682 6.06819C10.7439 5.89245 10.7439 5.60753 10.5682 5.43179C10.3924 5.25605 10.1075 5.25605 9.93179 5.43179L7.75 7.61358L5.56819 5.43179C5.39245 5.25605 5.10753 5.25605 4.93179 5.43179Z" fill="currentColor" fillRule="evenodd" clipRule="evenodd"></path>
              </svg>
            </div>
          </div>
          <Button 
            className="bg-slate-900 text-white hover:bg-slate-800 transition-colors w-full sm:w-auto h-10"
            onClick={handleGeneratePDF}
            disabled={isGenerating || !selectedPeriod}
          >
            {isGenerating ? (
              <>
                <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Generating...
              </>
            ) : (
              <>
                <Download className="w-4 h-4 mr-2" />
                Generate PDF
              </>
            )}
          </Button>
        </div>
      </div>

      {!selectedPeriod ? (
        <div className="flex-1 flex flex-col items-center justify-center border border-slate-200 border-dashed rounded-lg bg-white/50 backdrop-blur-sm min-h-[400px]">
          <div className="mb-4">
            <CalendarDays className="w-12 h-12 text-slate-300" strokeWidth={1.5} />
          </div>
          <h3 className="text-lg font-semibold text-slate-900 mb-1 tracking-tight">Select a period above</h3>
          <p className="text-sm text-slate-500 max-w-[280px] text-center mb-6">
            Your reconciliation report will preview here
          </p>
        </div>
      ) : (
        <div className="flex-1 flex flex-col gap-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Section 1 - Executive Summary */}
            <div className="col-span-1 md:col-span-2 bg-slate-50 border border-slate-200 rounded-xl p-6">
              <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-4">Executive Summary</h2>
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                <div>
                  <div className="text-xs text-slate-500 mb-1">Total transactions</div>
                  <div className="text-2xl font-bold text-slate-900">{stats.total}</div>
                </div>
                <div>
                  <div className="text-xs text-slate-500 mb-1">Auto-matched</div>
                  <div className="text-2xl font-bold text-slate-900">{stats.autoMatched} <span className="text-sm font-medium text-emerald-600">({stats.percentage}%)</span></div>
                </div>
                <div>
                  <div className="text-xs text-slate-500 mb-1">Manually reviewed</div>
                  <div className="text-2xl font-bold text-slate-900">{stats.manualReview}</div>
                </div>
                <div>
                  <div className="text-xs text-slate-500 mb-1">Exceptions resolved</div>
                  <div className="text-2xl font-bold text-slate-900">{stats.exceptions}</div>
                </div>
              </div>
              <div className="flex items-center gap-2 mt-4 pt-4 border-t border-slate-200">
                <Clock className="w-4 h-4 text-emerald-600" />
                <span className="text-sm font-medium text-emerald-700">
                  {timeSavedHours > 0 ? `Time saved this month: ~${timeSavedHours} hours` : "No transactions reconciled yet"}
                </span>
                {timeSavedHours > 0 && (
                  <span className="text-xs text-slate-400 ml-auto hidden sm:block">Based on 2 accountants × 3 min avg per transaction</span>
                )}
              </div>
            </div>

            {/* Section 4 - Health Score */}
            <div className="col-span-1 bg-white border border-slate-200 rounded-xl p-6 flex flex-col items-center justify-center text-center">
              <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-2 w-full text-left">Health Score</h2>
              <div className="flex-1 flex flex-col items-center justify-center">
                {healthScore !== null ? (
                  <>
                    <div className="flex items-baseline mb-2">
                      <span className={`text-6xl font-bold tracking-tighter ${
                        healthScore >= 80 ? 'text-emerald-600' : healthScore >= 60 ? 'text-amber-500' : 'text-rose-500'
                      }`}>{healthScore}</span>
                      <span className="text-xl font-medium text-slate-400 ml-1">/100</span>
                    </div>
                    <p className="text-sm font-medium text-slate-600 mt-2">
                      {healthScore >= 80 ? 'Excellent — above industry average of 78' : healthScore >= 60 ? 'Good — near industry average' : 'Needs attention'}
                    </p>
                  </>
                ) : (
                  <p className="text-sm text-slate-400">No data for this period</p>
                )}
              </div>
            </div>
          </div>

          {/* Section 2 - Match Rate Breakdown */}
          <div className="bg-white border border-slate-200 rounded-xl p-6">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-4">Match Rate Breakdown</h2>
            {totalNum > 0 ? (
              <>
                <div className="flex h-6 w-full rounded-full overflow-hidden mb-3 shadow-inner">
                  <div className="bg-emerald-500 h-full transition-all" style={{ width: `${autoPercent}%` }} />
                  <div className="bg-amber-400 h-full transition-all" style={{ width: `${manualPercent}%` }} />
                  <div className="bg-rose-500 h-full transition-all" style={{ width: `${exceptionPercent}%` }} />
                </div>
                <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs font-medium">
                  <div className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-emerald-500" />Auto-matched ({autoPercent}%)</div>
                  <div className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-amber-400" />Manual approval ({manualPercent}%)</div>
                  <div className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-rose-500" />Exceptions ({exceptionPercent}%)</div>
                </div>
              </>
            ) : (
              <p className="text-sm text-slate-400">No reconciliation data for this period.</p>
            )}
          </div>

          {/* Section 3 - Top Exceptions Table */}
          <div className="bg-white border border-slate-200 rounded-xl overflow-hidden mb-8">
            <div className="p-4 border-b border-slate-100 bg-slate-50">
              <h2 className="text-sm font-bold uppercase tracking-wider text-slate-700">Top Exceptions Summary</h2>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-slate-500 border-b border-slate-200 font-medium">
                  <tr>
                    <th scope="col" className="px-4 py-3">Date</th>
                    <th scope="col" className="px-4 py-3">Amount</th>
                    <th scope="col" className="px-4 py-3">Reason</th>
                    <th scope="col" className="px-4 py-3 text-right">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {topExceptions.map((item, index) => (
                    <tr key={item.id} className={`border-slate-100 hover:bg-slate-50 ${index < topExceptions.length - 1 ? 'border-b' : ''}`}>
                      <td className="px-4 py-3 text-slate-500">{item.date}</td>
                      <td className="px-4 py-3 font-mono font-medium whitespace-nowrap">
                        {item.amount < 0 ? "-" : ""}
                        {new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Math.abs(item.amount))}
                      </td>
                      <td className="px-4 py-3">
                        <span className="text-slate-700 font-medium">{item.reasonTag}</span>
                      </td>
                      <td className="px-4 py-3 text-right">
                        <span className={`inline-flex px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${item.statusColor}`}>
                          {item.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

